#!/bin/bash

# Colors to make the terminal beautiful and readable
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}==================================================${NC}"
echo -e "${BLUE}    Tickets Project - Environment Initializer     ${NC}"
echo -e "${BLUE}==================================================${NC}"

# 1. Check if Docker/Kubernetes is running
echo -e "\n${YELLOW}[1/4] Checking connection to Kubernetes...${NC}"
if ! kubectl cluster-info &> /dev/null; then
    echo -e "${RED}❌ Error: Docker Desktop or Kubernetes is not running!${NC}"
    echo -e "${RED}Please start Docker Desktop and try again.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Kubernetes is active!${NC}"

# 2. Create Namespace and Install ArgoCD
echo -e "\n${YELLOW}[2/4] Installing ArgoCD into the cluster...${NC}"
kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
kubectl apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

echo -e "${YELLOW}Exposing ArgoCD on localhost...${NC}"
kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'

# 3. Wait for CRDs to be ready
echo -e "\n${YELLOW}[3/4] Waiting for ArgoCD CRDs to be ready...${NC}"
echo "This might take a few seconds..."
kubectl wait --for=condition=established --timeout=60s crd/applications.argoproj.io
echo -e "${GREEN}✓ CRDs successfully installed!${NC}"

# 4. Apply GitOps Root Application
echo -e "\n${YELLOW}[4/4] Connecting cluster to GitOps (ArgoCD)...${NC}"
if [ -f "infrastructure/k8s/install-argo.yaml" ]; then
    kubectl apply -f infrastructure/k8s/install-argo.yaml
    
    # Fetch the default admin password generated by ArgoCD
    ARGO_PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)

    echo -e "${GREEN}==================================================${NC}"
    echo -e "${GREEN}🎉 SUCCESS! ArgoCD is now syncing the project.${NC}"
    echo -e "${BLUE}💻 Access the dashboard at: ${YELLOW}http://localhost${NC}"
    echo -e "${BLUE}👤 Username: ${YELLOW}admin${NC}"
    echo -e "${BLUE}🔑 Password: ${YELLOW}${ARGO_PASSWORD}${NC}"
    echo -e "${GREEN}==================================================${NC}"
else
    echo -e "${RED}❌ Error: File infrastructure/k8s/install-argo.yaml not found!${NC}"
    exit 1
fi