apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:3.7.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
              name: internal
          env:
            # Ativa explicitamente o modo KRaft nesta imagem
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            # Define o ID do cluster (podes usar o que o log gerou automaticamente)
            - name: KAFKA_CLUSTER_ID
              value: "5L6g3nShT-eMCtK--X86sw"
            # Onde a imagem da Apache vai guardar os metadados do KRaft internamente
            - name: KAFKA_VOLUME_DIR
              value: "/var/lib/kafka/data"
            
            # Configurações padrão do Broker
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:9092"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092