name: Booking Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'booking/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setting Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    # Como estamos num Monorepo, precisamos de dizer ao Maven para rodar 
    # DENTRO da pasta correta do microsserviço usando o 'working-directory'
    - name: Maven compile
      working-directory: ./booking
      run: mvn clean package -DskipTests # Se o mvnw estiver na raiz, usa ../mvnw

    - name:  Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build and push
      uses: docker/build-push-action@v5
      with:
        context: ./booking
        push: true
        tags: |
          luisfelipealves/booking-service:latest
          luisfelipealves/booking-service:${{ github.sha }}
    - name: Update booking-service tag in booking-deployment.yaml
      run: |
        sed -i 's|luisfelipealves/booking-service:.*|luisfelipealves/booking-service:${{ github.sha }}|g' infrastructure/k8s/booking-deployment.yaml
    - name: Commit and push changes to booking-deployment.yaml
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add infrastructure/k8s/booking-deployment.yaml
        git commit -m "chore(cd): update booking-service tag to ${{ github.sha }} [skip ci]"
        git pull --rebase origin main
        git push